{{- if .Values.nestedIf }}
# TEST: Nested if blocks
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-nested-if
data:
  base: "always"
{{- if .Values.nestedIf.level1 }}
  level1: "enabled"
{{- if .Values.nestedIf.level2 }}
  level2: "enabled"
{{- if .Values.nestedIf.level3 }}
  level3: "enabled"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
